name: Deploy Codelist

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: SSH VPS
        env:
            PRIVATE_KEY: ${{ secrets.CODELIST_SERVER_KEY  }}
            MONGO_KEY: ${{ secrets.MONGO_KEY  }}
            JWT_KEY: ${{ secrets.JWT_KEY  }}
            HOSTNAME: ${{ secrets.HOSTNAME  }}
            SSL_CERT: ${{ secrets.SSL_CERT  }}
            SSL_KEY: ${{ secrets.SSL_KEY  }}
            NOREPLY_PASSWORD: ${{ secrets.NOREPLY_PASSWORD  }}
        run: |
          echo "$PRIVATE_KEY" > private_key && chmod 600 private_key
          ssh -o StrictHostKeyChecking=no -i private_key root@${HOSTNAME} "tar --exclude='*node_modules*' -cvzf archive/Codelist_$(date +'%d-%m-%Y-%H-%M').tar.gz Codelist && rm -rf ./Codelist && git clone https://github.com/catalincd/Codelist && ./Codelist/deploy/deploy_script.sh $MONGO_KEY $JWT_KEY $NOREPLY_PASSWORD"
