on:
  push:
    branches: [ "master" ]
  workflow_dispatch:

env:
  NODE_VERSION: '18.x'

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./deploy
    steps:
      - name: Run deploy script
        run: ./deploy-script.sh ${{ secrets.CODELIST_SERVER_KEY }} ${{ secrets.JWT_KEY }} ${{ secrets.MONGO_KEY }}
        