name: Deploy Codelist

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: alpine-latest
    needs: deploy


    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Node.js 
      uses: actions/setup-node@v3
      with:
        node-version: 21.x

    - name: Install dependencies
      working-directory: ./frontend
      run: npm install

    - name: Create Env
      working-directory: ./frontend
      env:
        HOSTNAME: ${{ secrets.HOSTNAME  }}
        CLIENT_ID: ${{ secrets.CLIENT_ID  }}
      run: |
        echo "REACT_APP_HOSTNAME=https://$HOSTNAME" > .env
        echo "REACT_APP_GOOGLE_CLIENT_ID=$CLIENT_ID" >> .env
        echo "REACT_APP_REDIRECT_URI=https://$HOSTNAME/callback" >> .env
        cat .env
    
    - name: LS
      working-directory: ./frontend
      run: ls -ltrha

    - name: Build
      working-directory: ./frontend
      run: npm run build

    - name: Copy to server
      working-directory: ./frontend
      env:
          PRIVATE_KEY: ${{ secrets.CODELIST_SERVER_KEY  }}
          HOSTNAME: ${{ secrets.HOSTNAME  }}
      run: |
        echo "$PRIVATE_KEY" > private_key && chmod 600 private_key
        scp -r -o StrictHostKeyChecking=no -i private_key build/ root@${HOSTNAME}:/root/Codelist/server/

  deploy:
    runs-on: alpine-latest
    
    steps:
      - name: Run deploy script
        env:
            PRIVATE_KEY: ${{ secrets.CODELIST_SERVER_KEY  }}
            MONGO_KEY: ${{ secrets.MONGO_KEY  }}
            JWT_KEY: ${{ secrets.JWT_KEY  }}
            HOSTNAME: ${{ secrets.HOSTNAME  }}
            SSL_CERT: ${{ secrets.SSL_CERT  }}
            SSL_KEY: ${{ secrets.SSL_KEY  }}
            NOREPLY_PASSWORD: ${{ secrets.NOREPLY_PASSWORD  }}
            CLIENT_ID: ${{ secrets.CLIENT_ID  }}
        run: |
          echo "$PRIVATE_KEY" > private_key && chmod 600 private_key
          ssh -o StrictHostKeyChecking=no -i private_key root@${HOSTNAME} "tar --exclude='*node_modules*' -cvzf archive/Codelist_$(date +'%d-%m-%Y-%H-%M').tar.gz Codelist && rm -rf ./Codelist && git clone https://github.com/catalincd/Codelist && ./Codelist/deploy/deploy_script.sh $MONGO_KEY $JWT_KEY $NOREPLY_PASSWORD $CLIENT_ID"
  
      
          